# Generated by Django 3.1.4 on 2021-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210217_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
