# Generated by Django 3.1.4 on 2021-02-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mail_dtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
